Repository civictechdc/mango-tango-cli, pull requests merged in 2025-08, with the labels that each got.

#161 [DOCS] Redo(#149): Add config, documentation, and github workflow for mkdocs
  .github/workflows/docs.yml
  .gitignore
  .pre-commit-config.yaml
  .python-version
  README.md
  analyzer_interface/context.py
  docs/dev-guide.md
  docs/guides/contributing/analyzers.md
  docs/guides/contributing/contributing.md
  docs/guides/contributing/dashboards/react.md
  docs/guides/contributing/dashboards/shiny.md
  docs/guides/contributing/logging.md
  docs/guides/contributing/testing.md
  docs/guides/design-philosophy/architecture.md
  docs/guides/design-philosophy/content-domain.md
  docs/guides/design-philosophy/core-domain.md
  docs/guides/design-philosophy/edge-domain.md
  docs/guides/get-started/installation.md
  docs/guides/get-started/overview.md
  docs/img/favicon.ico
  docs/img/mango-text.png
  docs/index.md
  docs/license.md
  docs/reference/analyzer_interface.md
  docs/reference/app.md
  docs/reference/components.md
  docs/reference/importing.md
  docs/reference/meta.md
  docs/reference/preprocessing.md
  docs/reference/storage.md
  docs/reference/terminal_tools.md
  docs/reference/testing.md
  mkdocs.yml
  requirements-dev.txt
  requirements-mkdocs.txt
Labels: documentation

#194 [FIX, FEAT] Add support for native datetime formats, strip timezone information when importing string-based date columns
  analyzers/hashtags_web/app.py
  analyzers/hashtags_web/factory.py
  preprocessing/series_semantic.py
  preprocessing/test_series_semantic.py
Labels: domain: datasci, bugfix

#199 [RELEASE] v0.8.1-beta.1 (hotfix)
  pyinstaller.spec
Labels: bugfix
